feat: send letter page 구현
Lucky-pear/rwrw-web pull request #8
Opened 2021-02-05 02:58 UTC by juno7803

- useInput hook 사용(배열->객체로 변경)
- eslintrc.js 수정 :` '@typescript-eslint/explicit-module-boundary-types': 'error', -> 'off'`
- button 컴포넌트 재사용 가능하게 구현
- 공통된 header 컴포넌트 구현 후 Router 상단에 배치

2021-02-05 04:25 UTC, yjb94 requested changes
스타일 관련된 사항은 거의 리뷰에 담지 않았는데, Button 컴포넌트는 구조적으로 좀 문제가 있을 듯. 나중에 다시 다룹시다

2021-02-05 04:25 UTC, yjb94 commented on package.json
> +    "polished": "^4.1.0",
요거 머하는 기능입니까?

2021-02-05 04:25 UTC, yjb94 commented on src/App.tsx
> +          <Header />
Header를 정 넣고싶으년 `Router`에 넣는게 좋을 듯 싶슴당. App.tsx 규칙 참고

2021-02-05 04:25 UTC, yjb94 commented on src/Router.tsx
> +import Letter from './pages/Letter';
```suggestion
import LetterPage from './pages/LetterPage';
```

2021-02-05 04:25 UTC, yjb94 commented on src/Router.tsx
> +      <Route exact path="/letter" component={Letter} />
```suggestion
      <Route exact path="/letter" component={LetterPage} />
```

Page 네이밍 규칙 참고

2021-02-05 04:25 UTC, yjb94 commented on src/components/Button/Button.tsx
> +};
defaultlProps 대신 
```suggestion
const Button: React.FC<ButtonProps> = ({ children, color, bgColor, btnSize = 'mid', ...props }) => {
  return (
    <Wrapper color={color} bgColor={bgColor} btnSize={btnSize} {...props}>
      {children}
    </Wrapper>
  );
};
```

defaultProps 대신 걍 버튼 프로퍼티 default value 주는게 더 직관적일듯?

2021-02-05 04:25 UTC, yjb94 commented on src/styles/GlobalStyle.ts
> +    font-size: 10px;
이거 넣는건 좋은데 font-size가 default가 10px이 되는 문제를 해결하고 적용하는게 좋을듯. rem을 쓰지 않으면 무조건 10px일 듯?
1. <Text> 컴포넌트에 font-size를 1.6rem 으로 해서 사용하고 텍스트는 무조건 styled(Text)로 쓰게 한다
2. 그 외 방법

2021-02-05 04:25 UTC, yjb94 commented on src/pages/Letter.tsx
> +const Letter: React.FC = () => {
```suggestion
const LetterPage: React.FC = () => {
```
파일 이름도 바꿔줘야 함.

2021-02-05 04:25 UTC, yjb94 commented on src/pages/Letter.tsx
> +export default Letter;
```suggestion
export default LetterPage;
```
파일 이름도 바꿔줘야 함.

2021-02-05 04:28 UTC, yjb94 commented on package.json
> +    "polished": "^4.1.0",
보니까 yarn add 해놓고 참조 안하면서 안지웠네... 삭제죰

2021-02-05 04:34 UTC, juno7803 commented on package.json
> +    "polished": "^4.1.0",
아맞다... 저거 color에 opacity 주는 패키지인데 지울게요
ex) 호버시 원래 컬러에 살짝 어두워진 색이 뜨도록 함

2021-02-05 04:41 UTC, juno7803 commented on src/App.tsx
> +          <Header />
확인했습니다! `<BrowserRouter>` 바로 아래에 쓰는게 습관이었어서 저기다 썼음

2021-02-05 04:41 UTC, juno7803 commented on src/Router.tsx
> +import Letter from './pages/Letter';
resolved!

2021-02-05 04:41 UTC, juno7803 commented on src/Router.tsx
> +      <Route exact path="/letter" component={Letter} />
thx

2021-02-05 04:43 UTC, juno7803 commented on src/components/Button/Button.tsx
> +};
음 당장은 좋은거 같은데, 이건 뭔가 inline으로 작성하는 느낌일거같아서
뭔가 여러가지가 추가되면 defaultProps가 더 깔끔하지 않을까..? 그냥 더 깔끔한쪽이 어떤쪽일까 고민..

2021-02-05 04:46 UTC, juno7803 commented on src/styles/GlobalStyle.ts
> +    font-size: 10px;
이번에 해커톤이나 다른 프젝들에서 2번을 다들 썼고, 
디자이너가 건네준 피그마에 어차피 폰트사이즈가 16px인 경우가 거의 없었어서 대부분이 따로 지정해줘야 했었음
그래서 이렇게 했었어!

형이 하나를 정해주면 좋을듯?? 거기에 맞춰서 할게!

2021-02-05 04:46 UTC, juno7803 commented on src/pages/Letter.tsx
> +const Letter: React.FC = () => {
okay 반영완료

2021-02-05 04:47 UTC, juno7803 commented on src/pages/Letter.tsx
> +export default Letter;
okay 반영 완료

2021-02-05 04:47 UTC, yjb94 commented on src/components/Button/Button.tsx
> +};
개인적으로는 `defaultProps`는 뭔가 class component의 잔재같은 느낌이고(당시엔 props에 초기값및 interface type을 넣을 방법이 없었으니)
오히려 인라인으로 작성하는게 코드 작성 수고도 줄고 직관적인 것 같은뎅
@JangKyuBum @MrMirror21 의견 주십쇼

2021-02-05 04:51 UTC, yjb94 commented on src/styles/GlobalStyle.ts
> +    font-size: 10px;
1번으로 해서 Text로 지정해서 가져가는게 뭔가 확장성이 더 있을 것 같긴 한데... 웹은 리액트 네이티브처럼 Text 컴포넌트 안에서만 글씨를 쓸 수 있는게 아니라서 굳이 필요할까 싶기도 하넹
~거 디자이너분은 프로덕트 개발 많이 안해보셔서 16px이 근-본인걸 모르시는겔수도 있음~

이건 rem으로 권고하던 Text 컴포넌트를 사용하던 비슷할듯(?) 편한걸로 하시쥬

2021-02-05 08:30 UTC, MrMirror21 commented on src/components/Button/Button.tsx
> +};
둘 다 맞는 말이라 취향차 같긴 한데, 사실 준호 형이 말한대로 분리를 하더라도 위에 `ButtonProps` 있는 건 매한가지라 '분리해서 가독성을 높인다' 효과가 빛이 바래는 느낌이야

2021-02-05 08:31 UTC, MrMirror21 commented on src/styles/GlobalStyle.ts
> +    font-size: 10px;
1rem이 16px로 알고 있는데 아닌가유?

2021-02-05 08:59 UTC, yjb94 commented on src/styles/GlobalStyle.ts
> +    font-size: 10px;
@MrMirror21 1rem이 16px 맞을걸? 폰트 사이즈 디폴트가 16일겨

2021-02-06 07:48 UTC, yjb94 commented on src/styles/GlobalStyle.ts
> +    font-size: 10px;
@juno7803 이거 rem으로 쓰기로 하겠읍니당. 리드미 코드 규칙에 rem만 사용한다고 추가좀 해주세용

2021-02-06 07:49 UTC, yjb94 commented on src/components/Button/Button.tsx
> +};
@juno7803 다수결로 defaultProps 없애겠습니다

2021-02-09 18:02 UTC, yjb94 commented
@juno7803 readme 수정한거랑 defaultProps 반영한거 푸시해주세여ㅠㅠ 머지하고싶어요

2021-02-12 17:58 UTC, yjb94 approved these changes
LGTM :)

2021-02-12 17:58 UTC, yjb94 commented
@juno7803 confict만 해결하면 머지 해도 될듯

2021-02-13 04:14 UTC, merged